---

- name: set scylladb configuration files
  template:
    src:   "{{item.src}}"
    dest:  "/etc/scylla/{{item.dest}}"
    owner: scylla
    group: scylla
    mode:  0644
  with_items:
    - { src: 'scylla.yaml.j2', dest: 'scylla.yaml' }
    - { src: 'cassandra-rackdc.properties.j2', dest: 'cassandra-rackdc.properties' }

- name: set scylladb boot parameters
  template:
    src:  'scylla-server.j2'
    dest: '/etc/default/scylla-server'
    owner: root
    group: root
    mode:  0644

- name: set scylladb boot parameters
  template:
    src:  'scylla-jmx.j2'
    dest: '/etc/default/scylla-jmx'
    owner: root
    group: root
    mode:  0644

- name: set configuration files permissions
  file:
    path: '/etc/scylla'
    owner: scylla
    group: scylla
