---

- include: install.yml
  when: ansible_os_family == 'Debian'
  tag: [scylladb, scylladb-install]

- include: configure.yml
  tag: [scylladb, scylladb-config]

- include: service.yml
  tag: [scylladb, scylladb-service]
